import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';

const inter = Inter({ 
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'DMT Games Studio',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navigation />
                {children}
                <Footer />
            </body>
        </html>
    );
}
